### ISSUE TITLE
problem with latching with function 2 horn

### ISSUE THREAD

**Issue by renegad84** [flash62au/WiTcontroller#9]
When change in config_buttons.h  define latching is true, on all buttons where changed latching working but on #define ADDITIONAL_BUTTON_2_LATCHING true  not working its stay momentary when pressed.
![test](https://github.com/user-attachments/assets/75603557-6162-47e4-8f7e-29c4c718d6f5)

**Comment by flash62au** [comment]
are you using JMRI?

**Comment by renegad84** [comment]
yes and dcc-ex... on both is same

**Comment by flash62au** [comment]
a) What version of WitController are you using?
b) What command to you have assigned to **CHOSEN_ADDITIONAL_BUTTON_2_FUNCTION** ?

Can I get you contact me on Discord.  It will be a lot easier to work through this.
https://discord.gg/qtsFHwSM
Either post on the '**wifi-throttle**' channel or DM me --- **flash62au (Peter A)**

**Comment by flash62au** [comment]
Sorry, I just realised that you posted an image your button_config.

You don't have anything assigned to CHOSEN_ADDITIONAL_BUTTON_2_FUNCTION   It can do anything.
ADDITIONAL_BUTTON_2_LATCHING only comes into play if you are using the 6 additional optional buttons.

Do you just mean **Function 2** ?

**Comment by renegad84** [comment]
yes function 2 or F2

**Comment by flash62au** [comment]
If you have a roster entry for the loco it obeys whatever is in the roster entry. Otherwise it uses the defaults.

In JMRI, in the wiThrottle preferences, you can make F2 default to latching.
For DCC-EX you should be able to create a default roster entry, Address zero (0) and set the labels and latching to be whatever you want.

My alpha versions of Engine Driver has the ability to completely override the default labels and latching.  But they are not on the Play Store yet.

**Comment by renegad84** [comment]
Thank you for help, sorry for bothering you.

**Comment by flash62au** [comment]
no bother :-)
You're welcome.
